### ISSUE TITLE
Change icon Youtube

### ISSUE THREAD

**Issue by AraanBranco** [HubYard/HubYard#9]
From what I saw the Entypo has no icon to Youtube, it would be nice to exchange for something that symbolizes Youtube

Tip: entypo-play or entypo-video

**Comment by AraanBranco** [comment]
And add in css
.network-box - height: 80px

Once all boxes are at the same height and aligns the left button

**Comment by 4shub** [comment]
Noted,

**Comment by 4shub** [comment]
made a really lame icon but it works
